### ISSUE TITLE
Callbacks not called on Repo.preload()

### ISSUE THREAD

**Issue by rob-vetspire** [vereis/ecto_hooks#4]
For example:

```elixir
order = Repo.preload(order, :items)
# We expect that the callbacks have been called on each order item
# But the callbacks have not been called
```

**Comment by vereis** [comment]
You should be able to just copy these callbacks and adjust accordingly https://github.com/vereis/ecto_hooks/blob/main/lib/ecto_hooks/repo.ex#L256

**Comment by benonymus** [comment]
Hey, 
Is there a timeline for the preload support?

**Comment by vereis** [comment]
Hi @benonymus thanks for taking a look at this issue!

I think your fix looks pretty good; I'd you'd be happy to submit a PR, I don't think I have any qualms with including that change as part of a release I'll make sometime soon?

WDYT?

**Comment by benonymus** [comment]
Thanks @vereis, I would be happy to.

**Comment by pankamyk** [comment]
Hey @vereis,

Are there any plans of resolving this issue in foreseeable future? Are there some blockers with this ticket?

ps. thank you for this amazing package!

**Comment by vereis** [comment]
Hi all, sorry I dropped the ball on focusing on getting this released.

I've just tested and merged in @benonymus's PR -- thanks again for submitting it!

Published a new version of ecto hooks on hex.pm containing the new feature :-)
